openapi: 3.0.0
info:
  title: IBAPI
  version: '1.0'
servers: []
paths:
  /users/jake:
    post:
      summary: ''
      operationId: post-users-jake
      responses:
        '200':
          description: OK
components:
  schemas: {}
